version: "3"
services:
  express_app:
    container_name: api
    restart: always
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      PORT: 5000
      DB_HOST: "db"
      DB_PORT: 5432
      DB_USER: "postgres"
      DB_PASSWORD: "test_password"
      DB_NAME: "postgres"
      JWT_ACCESS_SECRET: "secret"
      JWT_REFRESH_SECRET: "refresh_secret"
      EXPIRE_IN: "30m"
      EXPIRE_REFRESH_IN: "30d"
      CLIENT_URL: "http://localhost:8080"

  db:
    container_name: postgres_db
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: "test_password"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  client_app:
    container_name: client
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
    ports:
      - "8080:8080"
    depends_on:
      - express_app

volumes:
  postgres_data:
